name: github pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  NEXT_PUBLIC_SEARCH_PATH: "https://code.flows.network/lambda/dElmOPdyu2"
  NEXT_PUBLIC_TWITTER_PRE_AUTH_PATH: "https://code.flows.network/lambda/cmdMywuHov"
  NEXT_PUBLIC_EMAIL_SEND_PATH: "https://code.flows.network/lambda/5lJ6t79rsm"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./site
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build
        run: |
          npm install
          npm run export

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/out

